### ISSUE TITLE
Basic main Game Loop

### ISSUE THREAD

**Issue by Kubaaa96** [Kubaaa96/Idle-Roman-Empire#1]
**TODO**
- [x] Setup Game class that will have instance in main function
- [x] Setup Engine class with basic game loop 
- [x] Setup Main window in Game constructor
