### ISSUE TITLE
Dynamic GUI windows system

### ISSUE THREAD

**Issue by Kubaaa96** [Kubaaa96/Idle-Roman-Empire#3]
**TODO**
- [x] Create Widget class and draw it as rectangle with Position, size and origin
- [x] Create Container class based on Widget 
- [x] Add sub Widgets to Container class
- [x] Create clickableWidget : Widget
- [x] Create Group : Container
- [x] Updating sub Widgets position when parent Widget change position
- [x] Create Basic BoxLayout : Group
- [x] Create VerticalBoxLayout : BoxLayout
- [x] Create HorizontalBoxLayout : BoxLayout
- [x] Create Button : ClickableWidget
- [x] Create Label : ClickableWidget
- [x] Create Panel : Group
- [x] Add Tests
- [x] Make LayoutStretch property in layouts

**Free thoughts**
- There will be one main windows per stage of Game
- Two version of Main Window with Back view (sub Windows based on Anchors) and without Back View (Windows Based on Layouts)
- Possibility to add Windows to main windows
- setup Layouts in sub Windows but not in Main Window in case of Window with Back view
- Setup Layout to Main window if There is not back view and only sub windows
-  Main way to setup new sub Windows based on anchors (TopLeft, TopRight, BottomLeft, Bottom Right)
- Possibility to add dragable window in middle of screen
- Possibility to add Window in certain position 
- Possibility to hide and show sub windows
- maybe possibility to Drag from one anchor and setup to another
- Possibility to have different Main Windows for different scenes
- Possibility to have the same Main Window Gui for different view
- For Dragable windows showing slots where can be added if not selected separate window at custom location
- Exporting/importing Gui Setup
